export const COMMANDS = {
    HELP: "Provides information on available commands and how to use them",
    EXPLAIN: "Explains the function or purpose of a specific item or command.",
    CONFIRM: "Confirms an action or decision.",
    CANCEL: "Cancels an ongoing action or discards a pending operation.",
    UNDO: "Reverts the last action performed.",
    REDO: "Re - applies an action that was just undone.",
    REPEAT: "Repeats the last executed command or action.",
    NOOP: "No operation; the input is not a recognized command.",
    GO_BACK: "Navigates back to the previous screen, page, or view.",
    GO_TO: "Navigates to a specific page, tab, or section.",
    SCROLL_UP: "Scroll the current view / page upwards.",
    SCROLL_DOWN: "Scrolls the current view / page downwards.",
    NEXT_ITEM: "Navigates to the previous item or entry in a list.",
    PREVIOUS_ITEM: "Navigates to the next item or entry in a list.",
    SELECT_ITEM: "Toggles the selection state of an item or chooses it.",
    SEARCH: "Searches for information or items based on a query.",
    FILL_FIELD: "Fills in a text field or input area with provided text.",
    CLEAR_FIELD: "Clears the content of a specific text field or input.",
    SUBMIT_FORM: "Submits the data entered in a form.",
}